### ISSUE TITLE
scala-rewrites rules need additional dependencies

### ISSUE THREAD

**Issue by ilmirons** [evis/scalafix-maven-plugin#90] opened 2023-04-25 10:25 UTC
Hi,

While I was trying to experiment with scala-rewrites rules I stumbled upon errors complaining about missing classes. (Specifically `metaconfig.pprint.TPrint` and ` scalafix/internal/config/ScalaVersion`). I solved both by including scalafix-core to the plugin dependencies. Below is my final working configuration. I think adding a note on the README.md about it would be useful.

```xml
<!-- scala.version.short: 2.12 -->
<!-- scalafix.version: 0.10.4 -->
<plugin>
                    <groupId>io.github.evis</groupId>
                    <artifactId>scalafix-maven-plugin_${scala.version.short}</artifactId>
                    <version>0.1.8_${scalafix.version}</version>
                    <dependencies>
                        <dependency>
                            <groupId>ch.epfl.scala</groupId>
                            <artifactId>scalafix-core_${scala.version.short}</artifactId>
                            <version>${scalafix.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.scala-lang</groupId>
                            <artifactId>scala-rewrites_${scala.version.short}</artifactId>
                            <version>0.1.3</version>
                        </dependency>
                        <dependency>
                            <groupId>org.typelevel</groupId>
                            <artifactId>typelevel-scalafix_${scala.version.short}</artifactId>
                            <version>0.1.4</version>
                        </dependency>
                    </dependencies>
                </plugin>
```

**Comment by bjaglin** [comment] 2023-06-04 21:36
This looks like a duplicate of https://github.com/scala/scala-rewrites/issues/155 - the rule must be published for it to work on scalafix 0.10+

**Closed** 2023-08-06 15:02 UTC
